### ISSUE TITLE
创建的视频片段的起点在时间0点之前。

### ISSUE THREAD

**Issue by WyvernZhao** [opencodewin/MediaEditor#22]
当时间轴中只有一条视频轨道时，向时间轴中拖入并创建第二个视频片段在空白区域，这样会创建一条新的视频轨道，注意鼠标在释放视频素材时，位置需要停留在轨道头部区域，也就是时间0点之前。这样操作后创建出来的视频片段，其起始点在时间0点之前，这是错误的结果，视频片段的起始点不应该小于时间0点。

**Comment by DickyQi** [comment]
fixed it, but we may consider to allow add new clip on track which start time is negative
