### ISSUE TITLE
将两个视频片段首尾相连后，无法向右方拖动后部的片段，应该是磁吸效果导致的错误结果。

### ISSUE THREAD

**Issue by WyvernZhao** [opencodewin/MediaEditor#25]
并不是每个文件都能触发该bug，目前发现最简单的重现方法是使用bwbj_hq_clip1.mp4文件，进行如下操作：
1. 空白时间轴区域。
2. 将bwbj_hq_clip1.mp4素材拖入时间轴产生一组音视频的片段。
3. 再次将该素材拖入时间轴产生一组新的片段，并置于第一次的片段后面。
4. 拖动第二次的片段向前移动，使其与第一次的片段首尾相连，产生磁吸效果后松开鼠标，完成移动操作。
5. 点击第二次的片段（后面的片段）向右方拖拽，会发现无法移动该片段，这是错误的反应。

**Comment by DickyQi** [comment]
fixed
