### ISSUE TITLE
在片段上点击鼠标右键无法唤出右键菜单。

### ISSUE THREAD

**Issue by WyvernZhao** [opencodewin/MediaEditor#26]
在一个视频片段上点击右键，不能唤出右键菜单，且之后无法进行seek操作。

**Comment by feliwir** [comment]
Could you please write the issue descrptions in english? I think the majority of people in the internet only understand english language. Thanks :)

**Comment by DickyQi** [comment]
This issue is fixed. Last change cause imgui popup dialog missing paired
