### ISSUE TITLE
[Linux ] application does not close on ctrl+c

### ISSUE THREAD

**Issue by feliwir** [opencodewin/MediaEditor#27]
Probably SIGINT is not handled correctly

**Comment by feliwir** [comment]
Any program than can be started from the commandline should close on "ctrl+c".  `SIGINT` is also emitted from the task manager for example, so this causes other issues aswell

**Comment by WyvernZhao** [comment]
> Any program than can be started from the commandline should close on "ctrl+c". `SIGINT` is also emitted from the task manager for example, so this causes other issues aswell

I agree with you that a program started from the terminal should be able to exit on "ctrl+c". Although I usually run a AppImage program by double clicking the icon, it can also be started from the command line by simply execute it. So I tested the case you metioned under my ubuntu 22.04, but I got the different result, the program exited normally when I pressed "ctrl+c". I cannot reproduce this issue with my computer.
![quit-with-ctrl-c](https://user-images.githubusercontent.com/10590584/233601775-409ebf79-aba5-4084-93bf-d83df632a84a.png)

**Comment by feliwir** [comment]
I didn't generate an AppImage - i just ran the compiled binary like this:
```
[stephan@fedora build]$ ./mec
^C^C
```
Nothing happens at all

**Comment by WyvernZhao** [comment]
Ok, I tested running the executable "mec" from build directory as you described. But still I can quit it by "ctrl+c". I think it probably has something to do with OS environment. Could you share your OS information?

**Comment by feliwir** [comment]
```
             .',;::::;,'.                stephan@fedora 
         .';:cccccccccccc:;,.            -------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 38 (Workstation Editi 
    .:cccccccccccccccccccccccccc:.       Kernel: 6.2.11-300.fc38.x86_64 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Uptime: 1 day, 20 hours, 47 mins 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Packages: 2614 (rpm), 48 (flatpak) 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Shell: bash 5.2.15 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Resolution: 1920x1080, 1920x1080 
:cccccccccccccc;MMM.;cccccccccccccccc:   DE: GNOME 44.0 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   WM: Mutter 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM Theme: Adwaita 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: Adwaita [GTK2/3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: gnome-terminal 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: NVIDIA GeForce GTX 1660 SUPER 
:cccccccccccccccccccccccccccc:'.         Memory: 18577MiB / 32002MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                                                                                       
```

**Comment by WyvernZhao** [comment]
Thanks @feliwir  for your kindly share. We will try to reproduce this issue after we setup a similar env. But that may take some days or even longer because we've got many other stuffs to deal with and Fedora is kind of new to me.
