### ISSUE TITLE
[Linux] Window is missing any decorations

### ISSUE THREAD

**Issue by feliwir** [opencodewin/MediaEditor#28]
It's not possible to close MediaEditor, since the window is missing any close buttons in the window bar:
![image](https://user-images.githubusercontent.com/2104576/233580816-30073744-8418-45cc-8b37-6322428670fb.png)

**Comment by DickyQi** [comment]
we using full screen window for application. and at left side menu toolbar. Last button is quit button, you can click it to exit app.

**Comment by WyvernZhao** [comment]
There two ways to quit MEC under ubuntu:
1. By clicking the "quit" button on the left tool bar.
![quit-1](https://user-images.githubusercontent.com/10590584/233590996-41e6a367-93a4-44f4-abc7-de7ab7c9acfe.png)
2. By clicking the "mec" task bar icon then click the "quit" menu item.
![quit-2](https://user-images.githubusercontent.com/10590584/233591064-08d19a4b-cac5-4b96-99ac-b84da93d1ef5.png)

**Comment by feliwir** [comment]
> we using full screen window for application. and at left side menu toolbar. Last button is quit button, you can click it to exit app.

The window is not fullscreen.
I think people are used to having a "X" in the top-right corner.
