### ISSUE TITLE
win32 build

### ISSUE THREAD

**Issue by codz01** [opencodewin/MediaEditor#30]
Hi
this app looks amazing but unfortunately i have win32 system , do you plan to add a win32 build ? , 
thanks

**Comment by WyvernZhao** [comment]
Sorry, we don't have a plan to support win32 for now. Besides that, 32bit OS can only support the memory no more than 4GB size, and that is too low to perform most of the work in non-linear editing.

**Comment by codz01** [comment]
thanks for the answer , fair enough
