### ISSUE TITLE
Apple M1 chip - illegal hardware instruction

### ISSUE THREAD

**Issue by JoySeeDog** [opencodewin/MediaEditor#32]
Apple M1 chip can not open  /MediaEditor/build/mec.app/Contents/MacOS/mec , error is :
 

➜  ~ /Users/xxx/Code/MediaEditor/build/mec.app/Contents/MacOS/mec ; exit;
[1]    71976 illegal hardware instruction  /Users/xxx/Code/MediaEditor/build/mec.app/Contents/MacOS/mec

Saving session...completed.

[Process completed]

**Comment by sizeofbeer** [comment]
I need more compile-related information to check for the error.

**Comment by sizeofbeer** [comment]
if you use vscode to launch, you can try add -->   "targetArchitecture": "x86_64"    <-- in "launch.json" file

**Comment by JoySeeDog** [comment]
not compile error，it is run error

**Comment by sizeofbeer** [comment]
ohh, if you run mec in m1, you need check you download dmg. apple M1 card is arm-architecture rather than x86.
==> https://github.com/opencodewin/MediaEditor/releases/download/v0.9.6/MEC_SDL2_OpenGL3-macos-arm64-0.9.6.dmg

**Comment by JoySeeDog** [comment]
Thanks！
