### ISSUE TITLE
when use "preview out", front-layer resolution is different

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#38]
It will cause the left and right picture is not alignment
<img width="1213" alt="image" src="https://github.com/opencodewin/MediaEditor/assets/26289650/6f442f8c-3387-452e-bfd5-3b56bc96b93c">

**Comment by DickyQi** [comment]
preview out display image may be resized or moved by any custom operations, so it is hard to align left/right view. Compare viewer is only for some filters which effect image details.
