### ISSUE TITLE
behavior inconsistent, between clip timeline and main timeline  

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#42]
1. frame alignment position is inconsistent in the frame accuracy.
2. when zoom clip timeline, appear black snapshots with "?".

<img width="757" alt="1" src="https://github.com/opencodewin/MediaEditor/assets/26289650/acc7b6e8-08ee-4130-b1a8-c172de7a9ca5">
<img width="757" alt="1" src="https://github.com/opencodewin/MediaEditor/assets/26289650/7852ff92-6900-419f-9192-6e5e27e00b8a">

**Comment by DickyQi** [comment]
different timeline in same UI cause user confused, need find new method
