### ISSUE TITLE
Can't open transition-editing page

### ISSUE THREAD

**Issue by CodeDiseaseDev** [opencodewin/MediaEditor#46]
https://github.com/opencodewin/MediaEditor/blob/master/docs/dev/Quick-Start.md#add-transitions

i'm unable to enter the transition-editing page, pretty sure i held down shift and double clicked correctly...................

![image](https://github.com/opencodewin/MediaEditor/assets/70626250/2afb91f8-db33-43e5-a089-87f4776423c4)

im running windows 11

it looks like this after i shift + double click
![image](https://github.com/opencodewin/MediaEditor/assets/70626250/1d214b76-546a-49b6-b268-55d54c0036d1)

**Comment by WyvernZhao** [comment]
It's not stated clearly that there are two different response area in a video clip to the 'double-click' opreation. Looks like you were clicking in the TITLE area of the video clip, that would result in a collapse of the clip. Try double click in the SNAPSHOT area, then the UI should change to the video effect editing layout.

**Comment by WyvernZhao** [comment]
It's not stated clearly that there are two different response area in a video clip to the 'double-click' opreation. Looks like you were clicking in the TITLE area of the video clip, that would result in a collapse of the clip. Try double click in the SNAPSHOT area, then the UI should change to the video effect editing layout.

Transition is another thing. You should place two video clips in the timeline, and make an overlap out of them. Then you can double click the overlap area to enter the transition editing layout.
