### ISSUE TITLE
The drawing of the timeline area loses a lot of elements, after the media analysis area is separated from the main window 

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#47]
<img width="1798" alt="SCR-20230727-o1i" src="https://github.com/opencodewin/MediaEditor/assets/26289650/facc86f2-07c2-4665-9138-b357f5749048">

**Comment by DickyQi** [comment]
MacOS OpenGL vertex count limited is weird. If we using vulkan as rendering backend, the problem isn't appeared. Audio track waveform preview toke too many drawing vertex, so we need find a new method to handle waveform preview.

**Comment by DickyQi** [comment]
fixed it, on integrate GPU, do not using BufferSubData(always not used).
