### ISSUE TITLE
Select "Audio Vector" under the "Vector Mode" of any option, the overall picture suddenly brightens

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#48]
<img width="1614" alt="SCR-20230727-o3s" src="https://github.com/opencodewin/MediaEditor/assets/26289650/40655c09-40b6-4f8e-96bd-13bccdfbebd7">

**Comment by DickyQi** [comment]
because popup menu(combo widget) is out of current window 's viewport, we fixed it by set popup window viewport with parent viewport.
