### ISSUE TITLE
Select the event, then drag the clip timeline ruler and move the mouse pointer over any of the event rectangles. The ruler and the event are moved together

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#49]
<img width="507" alt="SCR-20230727-o8w" src="https://github.com/opencodewin/MediaEditor/assets/26289650/c3df0eb6-c0f3-4c7d-ae63-403554a415a2">

**Comment by DickyQi** [comment]
fixed it
