### ISSUE TITLE
Stop at Splash-Window when opening software for the first time!

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#54]
![image](https://github.com/opencodewin/MediaEditor/assets/26289650/a7c2cd5c-0a1e-4f47-be79-c79a59441d55)

Notebook: Apple Macbook Pro M1(Pro)
OS: macOS Somoma 14.2.1
H2R:
1. clean all mec's profile(ini file, such as 'mec.ini'; project file, such as 'test.mep')
2. open the software(mec, debug)

Remark: when opening the software again, it can be accessed normally.

**Comment by DickyQi** [comment]
fixed it, please test.
