### ISSUE TITLE
Timeline area is not responding(UI, any op), due to done some combination operations

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#57]
Situation: just no response at timeline area

Notebook: Apple Macbook Pro M1(Pro)
OS: macOS Somoma 14.2.1
H2R:
1. after jumping to editing video/audio clip, then add filter to event area(no click this event) and zip the filter's param-setting area(right side)
2. click the delete button(right side)
<img width="1197" alt="image" src="https://github.com/opencodewin/MediaEditor/assets/26289650/8d3cf3dd-529d-46e3-98e1-c7c4720961f8">
3. close this video/audio clip edit page
4. at moment, clicking on timeline area is no response.
<img width="251" alt="image" src="https://github.com/opencodewin/MediaEditor/assets/26289650/1fe250f1-76d2-4cdd-b770-b5c20db3e0fb">

**Comment by DickyQi** [comment]
Fixed it, please test it
