### ISSUE TITLE
After adding mask for filter event. Delete the filter, but the mask box still exists.

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#58]
Situation: above title

Notebook: Apple Macbook Pro M1(Pro)
OS: macOS Somoma 14.2.1

<img width="269" alt="SCR-20240131-fpz" src="https://github.com/opencodewin/MediaEditor/assets/26289650/60bfcc3c-940e-43f9-8314-c589ce22fb05">

**Comment by WyvernZhao** [comment]
Fixed this issue in commit ff1313e0514a5c85f346a1f9e8fef874157c0e29.
