### ISSUE TITLE
After adding mask for filter event. In addition to being effective within the mask box, it's also affected by this filter at the edges of the ImageView.

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#59]
Situation: above title

Notebook: Apple Macbook Pro M1(Pro)
OS: macOS Somoma 14.2.1

<img width="200" alt="SCR-20240131-fql" src="https://github.com/opencodewin/MediaEditor/assets/26289650/cf1e620b-529b-4d80-b41f-b2fa859d85ee">

**Comment by WyvernZhao** [comment]
Fixed this issue by commit c33ed45af1b2973c65cb0206fcea782fe3454358.
