### ISSUE TITLE
FF api 'avio_open' returns error! fferr=-2

### ISSUE THREAD

**Issue by AlphaNERD-** [opencodewin/MediaEditor#60]
Hello,

i wanted to export a video i made with the Media Editor. Unfortunately when i click the button "Start encoding", i get the error depicted in the title.

I tried this on 2 machines with different hardware.

Machine 1:
Name: GPD Win Mini
CPU: AMD Ryzen 7 7840U, 8 Cores / 16 Threads @ 3,3 GHz
GPU: AMD Radeon 780M, 16 GB RAM
RAM: 64GB DDR5
OS: Windows 11 23H2

Machine 2:
Name: Asus G20AJ
CPU: Intel Core i5 4460, 2 Cores / 4 Threads @ 3,2 GHz
GPU: NVidia GeForce GTX 970, 4 GB VRAM
RAM: 16 GB DDR3
OS: Windows 10 1809

**Comment by WyvernZhao** [comment]
Thank you for your feed back on our MEC :) Sorry for the inconvenience that encoding is not working on your machine.
It's weird that ffmpeg api 'avio_open' returns -2 on the encoding procedure. After I checked the code of ffmpeg, I see that -2 means `#define	ENOENT		 2	/* No such file or directory */`. So what is the export path you were using? Is there any inexisting intermediate directories in your export path? We're not checking and creating these inexisting directories for now, so you need to make sure that the parent directory of the export path must be existed. And another thing you should confirm is that you have the permission to create and write files in the path you choose.
