### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by AlphaNERD-** [opencodewin/MediaEditor#62]
Hello again,

so i wanted to make a meme and use some cutting and greenscreen trickery for that. One step was to add a still frame from a video as a JPEG, stretch the playback duration and animate stuff on top of it through more video layers

However Media Editor doesn't render JPEGs reliably. Initially i thought that the Chroma Key filter was broken, but after some testing i realized that the rendering of the JPEG itself is broken. I could work around that seemingly by frequently restarting the software and messing with the video tracks.

I wanted to add the still frame as a PNG, however that immediately crashes Media Editor. The same happens with other image formats like TIFF, GIF, etc. I also downloaded a PNG from another source and that too crashes Media Editor immediately.

I attached a ZIP file with files i got Media Editor to crash with and a JPEG with gave me a headache.

[Crashes.zip](https://github.com/opencodewin/MediaEditor/files/14146046/Crashes.zip)
![Not rendered](https://github.com/opencodewin/MediaEditor/assets/9458093/0e132b2e-fffe-4f9a-a8af-b22c632deb65)

**Comment by WyvernZhao** [comment]
Thank you for your feed back:) We've downloaded the 'Crashes.zip' you attached, and tested the image files in it. We've fixed the issue on displaying these images in the commit 2a31b423702a901bcd6cd20bc6d4d912f6238788. You need to build MEC from the latest code if you can. If you need us to provide a built executable for you, please leave the OS information you want us to build upon. I think you need windows version, right?

**Comment by AlphaNERD-** [comment]
Yes, Windows is correct. Thank you for the build in advance :)Am 05.02.2024 um 04:16 schrieb Wayne Zhao ***@***.***>:﻿
Thank you for your feed back:) We've downloaded the 'Crashes.zip' you attached, and tested the image files in it. We've fixed the issue on displaying these images in the commit 2a31b42. You need to build MEC from the latest code if you can. If you need us to provide a built executable for you, please leave the OS information you want us to build upon. I think you need windows version, right?

**Comment by WyvernZhao** [comment]
Hello, I've built a temporary version for windows. You can get it from [https://drive.google.com/file/d/1uxi2LZuQwkc0fXjJyUz8BX-tS4BedJXX/view?usp=drive_link](here). MEC has changed a lot from v0.9.8, since it's been nearly half a year passed from last release. The old project file (.mep file) may not be loaded successfully. My reccommandation is to create a new project if possible.

**Comment by DickyQi** [comment]
fixed issue on 0.9.9
