### ISSUE TITLE
windows how to use the vs2019 to compile it?

### ISSUE THREAD

**Issue by xinsuinizhuan** [opencodewin/MediaEditor#68]
![图片](https://github.com/opencodewin/MediaEditor/assets/40679769/e296c73c-6510-439e-bfe3-51dbe30224ee)

Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

**Comment by WyvernZhao** [comment]
Sorry, we don't support compile this project using MSVC compiler. Under windows, please use gcc/clang under mingw environment, download and install msys2 can establish a usable dev environment easily.
