### ISSUE TITLE
Crash after playing previous file backwards without pressing Stop after

### ISSUE THREAD

**Issue by Ivi104** [opencodewin/MediaEditor#69]
Steps to reproduce:
1. Add 2 different (short) .ogg files to media bank. (I used files from https://warframe.fandom.com/wiki/Acolytes/Quotes)
2. Drag the first file to timeline
3. Skip to the end using button below preview
4. Click Reverse below preview to play the audio backwards. Allow the file to play completely and stop on its own. Do NOT press the Stop button.
5. Delete the played file from the timeline
6. Drag the second file to timeline

The last step ends with a crash, reproduced 3/3 times
If the Stop button is pressed after step 4, the crash does not happen.

Using mec 0.9.9.240227 Community on Windows 11 Pro 23H2, OS build 22631.3447

**Comment by WyvernZhao** [comment]
Thank you for your feedback, I'll look into it.

**Comment by WyvernZhao** [comment]
Fixed this issue in 72680f1f12e1754c2ae2b6a585ae87a88cc29230.
