### ISSUE TITLE
Unable to build due to missing source code of the binary blobs in extralib folder

### ISSUE THREAD

**Issue by M0n7y5** [opencodewin/MediaEditor#71]
For some reason you decided to hide source of the mediacore lib + other dependencies. Due to this change, its no longer possible to build version 0.9.9 due to repo submodules pointing at hidden/private repo.
In other words, nobody can pull the submodules needed for building the app.

Also due to closed source libs/blobs in extralib folder, latest commit also fails due to missing symbols in those closed source libs.
Please allow the source to be downloaded so its possible for users to build the app again. 

Due to this issue nobody is able to contribute to this project.

**Comment by M0n7y5** [comment]
bump

**Comment by M0n7y5** [comment]
:eye:

**Comment by DickyQi** [comment]
We are working for put back dependence code. Please wait a little time as we short of resource.

**Comment by M0n7y5** [comment]
You should close this after you resolve the issue. Not before. smh
