### ISSUE TITLE
MacBook M1 Pro在多片段使用filter时播放预览画面不动

### ISSUE THREAD

**Issue by sizeofbeer** [opencodewin/MediaEditor#8]
例如，在某段时间线区间存在两个视频片段(分布在上下两个视频轨道上)，一个片段使用canny filter，另一个使用guided filter，此时点击播放，预览画面不动。
另外，MacBook M1 Pro的GPU使用率为100%。

**Comment by DickyQi** [comment]
we will persistent optimize.
